swagger: "2.0"

info:
  title: "Document GPT searcher"
  version: "1.0"
  description: "This is a simple minimal REST API microservice to perform searches over a vectorDB containing processed embeddings.\n"
  contact:
    name: Marco Colombo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

basePath: /v1

schemes:
 - http

paths:
  /search:
    post:
      tags:
      - query
      operationId: api.search
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: user_payload
        description: Query over data
        schema:
          $ref: '#/definitions/Query'
          type: object
      responses:
        '200':
          description: 'Result from search over indexed data'
          schema:
            $ref: '#/definitions/Answer'
        400:
          description: invalid input
        500:
          description: internal server error

definitions:
  Query:
    type: object
    properties:
      question:  { type: string }
  Answer:
    type: object
    properties:
      question:  { type: string }
      answer:  { type: string }
